AWSTemplateFormatVersion: 2010-09-09
Description: Template for Lambda and API gateway

Parameters:
  S3Bucket:
    Description: S3 Bucket of assets
    Type: String

  S3Key:
    Description: S3 Bucket of assets
    Type: String

  ChinaRegion: 
    Description: Check if the stack to be in CN Region
    Type: String
    Default: false
    AllowedValues: [ true, false ]

Conditions:
  Globally: !Equals [ false, !Ref ChinaRegion ]

Resources:
  HelperLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      Content:
        S3Bucket: !Ref S3Bucket
        S3Key: !Sub ${S3Key}codes/industry_ai_helper.zip
      Description: Helper layer for DynamoDB, SSM, ane ES
      LayerName: industry_ai_helper
      LicenseInfo: MIT

  SageMakerLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      Content:
        S3Bucket: !Ref S3Bucket
        S3Key: !Sub ${S3Key}codes/industry_ai_sagemaker.zip
      Description: SageMaker layer
      LayerName: industry_ai_sagemaker
      LicenseInfo: MIT

  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      EndpointConfiguration:
        Types:
          - REGIONAL
      Parameters:
        endpointConfigurationTypes: REGIONAL
      BinaryMediaTypes:
        - 'image/png'
        - 'image/jpg'
        - 'image/jpeg'
      Name: industry-ai-api
      Policy: 
        !If
          - Globally
          - Version: 2012-10-17
            Statement: 
              - Effect: Allow
                Principal: '*'
                Action: 'execute-api:Invoke'
                Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
          - Version: 2012-10-17
            Statement: 
              - Effect: Allow
                Principal: '*'
                Action: 'execute-api:Invoke'
                Resource: !Sub 'arn:aws-cn:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'

  ApiGatewayResourceInference:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: 'inference'
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayMethodInferencePost:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: 
          !If
          - Globally
          - !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AllInOneAIInferenceFunction.Arn}/invocations'
          - !Sub 'arn:aws-cn:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AllInOneAIInferenceFunction.Arn}/invocations'
      ResourceId: !Ref ApiGatewayResourceInference
      RestApiId: !Ref ApiGatewayRestApi   

  AllInOneAIInferenceFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - !If
          - Globally                                                  
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
          - 'arn:aws-cn:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
        - !If
          - Globally                                                  
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'
          - 'arn:aws-cn:iam::aws:policy/service-role/AWSLambdaRole'
  
  AllInOneAIInferenceFunctionAdditionalPermission:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: industry_ai_inference
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'logs:*'
              - 'lambda:*'
              - 'cloudwatch:*'
            Resource: '*'
            Effect: Allow
      Roles:
        - !Ref AllInOneAIInferenceFunctionRole

  AllInOneAIInferenceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Sub ${S3Key}codes/industry_ai_inference.zip
      FunctionName: industry_ai_inference
      Tags:
        - Value: Name
          Key: 'AllInOneAIApi'
      Handler: lambda_function.lambda_handler
      Role: !GetAtt AllInOneAIInferenceFunctionRole.Arn
      Timeout: 900
      Runtime: python3.9

  AllInOneAIInferenceFunctionCatchAllPermissionProd1:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com      
      FunctionName: !Ref AllInOneAIInferenceFunction
      SourceArn: 
        !If
        - Globally
        - !Sub
          - >-
            arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/POST/inference
          - __Stage__: '*'
            __ApiId__: !Ref ApiGatewayRestApi
        - !Sub
          - >-
            arn:aws-cn:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/POST/inference
          - __Stage__: '*'
            __ApiId__: !Ref ApiGatewayRestApi

   
  AllInOneAIInvokeEndpointFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - !If
          - Globally                                                  
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
          - 'arn:aws-cn:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
        - !If
          - Globally                                                  
          - 'arn:aws:iam::aws:policy/AmazonSageMakerFullAccess'
          - 'arn:aws-cn:iam::aws:policy/AmazonSageMakerFullAccess'
    
  AllInOneAIInvokeEndpointFunctionAdditionalPermission:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName:   industry_ai_invoke_endpoint
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'logs:*'
              - 'lambda:*'
              - 'cloudwatch:*'
            Resource: '*'
            Effect: Allow
      Roles:
        - !Ref AllInOneAIInvokeEndpointFunctionRole

  AllInOneAIInvokeEndpointFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Sub ${S3Key}codes/industry_ai_invoke_endpoint.zip
      FunctionName: industry_ai_invoke_endpoint
      Tags:
        - Value: Name
          Key: 'AllInOneAIApi'
      Handler: lambda_function.lambda_handler
      Role: !GetAtt AllInOneAIInvokeEndpointFunctionRole.Arn
      Timeout: 900
      Runtime: python3.9
      Layers:
        - !Ref SageMakerLayer


Outputs:
  ApiGatewayProdEndpoint:
    Description: "API Prod stage endpoint"
    Value: 
      !If
      - Globally
      - !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod
      - !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com.cn/Prod
